mode: medium_01
plan_list:
- - -4.0
  - 20.0
  - -0.3
  - 0.47
  - 2.0
  - 2024_07_05_16_13_43/postprocess/shadow.pth
  - ConstantPlanner
  - {}
iteration: 30000
sh_degree: 3
load_HD_map: true
white_background: false
data_device: cpu
data_type: nuscenes
start_euler:
- 0.0
- 0.0
- 0.0
start_ab:
- 0.0
- 0.0
start_velo: 1
start_steer: 0
target: 60
scene_name: scene-0062
affine: false
quiet: false
ignore_dynamic: false
unicycle: false
