realcar_path: /data/guest_rui/ztrs_workspace/HUGSIM/assets/3DRealCar
model_base: /data/guest_rui/hugsim_nusc/models
uniad_path:  /nas/users/hyzhou/PAMI2024/release/UniAD_Sim/tools/e2e.sh
vad_path:  /nas/users/hyzhou/PAMI2024/release/VAD_Sim/tools/e2e.sh
ltf_path: /nas/users/hyzhou/PAMI2024/release/navsim/ltf_e2e.sh
output_dir: /data/guest_rui/hugsim_outputs/benchmark/out/nusc_
HD_map:
  path: /data2/dataset/nuscenes
  version: nusc_trainval
