realcar_path: /bigdata/jason/drivor_evaluation/HUGSIM/3DRealCar
model_base: /bigdata/datasets/HUGSIM/scenes/nuscenes
uniad_path: ""
vad_path: ""
ltf_path: ""
output_dir: /bigdata/aidan/outputs/benchmark/out/nusc_
HD_map:
  path: /bigdata/datasets/nuscenes
  version: nusc_trainval
