drivor:
  launch_path: ./planners/drivor/launch.sh
  repo_root: /bigdata/aidan/DrivoR
  checkpoint: /bigdata/aidan/DrivoR/weights/checkpoints/drivor_Nav1_25epochs.pth
  dino: /bigdata/aidan/DrivoR/weights/vit_small_patch14_reg4_dinov2.lvd142m
  python_bin: /bigdata/aidan/.home/envs/drivor/bin/python3.8
  config: /bigdata/aidan/DrivoR/navsim/planning/script/config/common/agent/drivoR.yaml

  device: cuda
  image_scale: 0.4
