drivor:
  launch_path: ./planners/drivor/launch.sh
  repo_root: /home/jiageng/DrivoR
  checkpoint: /home/jiageng/DrivoR/weights/checkpoints/drivor_Nav1_25epochs.pth
  dino: /home/jiageng/DrivoR/weights/vit_small_patch14_reg4_dinov2.lvd142m
  python_bin: /home/jiageng/miniconda3/envs/navsim/bin/python
  config: /home/jiageng/DrivoR/navsim/planning/script/config/common/agent/drivoR.yaml

  device: cuda
  image_scale: 0.4
